steps:
  - name: node
    entrypoint: npm
    dir: "todo-list/"
    args: ["run", "deploy"]

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["-q", "app", "deploy"]

# Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/pizza-store-nimg/example-1", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/pizza-store-nimg/example-1"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
       "deploy",
        "service-4",
        "--image",
        "gcr.io/pizza-store-nimg/example-1",
        "--region",
        "us-central1",
        "--platform","managed",'--port',"8000","--allow-unauthenticated"
      ]
images:
  - gcr.io/pizza-store-nimg/example-1
timeout: 1800s
